name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  location:  # id of input
    description: 'URL of the page to test'
    required: false
    default: 'http://localhost:8080/index.html'
outputs:
  axe-results-location: # id of output
    description: 'File with results of the axe CLI run'
runs:
  using: 'node12'
  main: 'dist/index.js'