name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  location:
    description: 'URL of the page to test'
    required: false
    default: 'http://localhost:8080/index.html'
  load-delay:
    description: 'Milliseconds of delay to use'
    required: false
    default: '0'
  fail-on-violation:
    description: 'Set failure code after violation'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'