name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  build-config-file:  # id of input
    description: 'Location of the config file to use for build'
    required: false
    default: 'ui5.yaml'
  serve-config-file:  # id of input
    description: 'Location of the config file to use for serve'
    required: false
    default: 'ui5.yaml'
outputs:
  axe-results-location: # id of output
    description: 'File with results of the axe CLI run'
runs:
  using: 'node12'
  main: 'dist/index.js'